branches:
  only:
    - master
language: python
python:
  - "3.9"
before_install:
  - pip install -U pip
  - pip install codecov
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest
codecov:
  - codecov
